### ISSUE TITLE
Expose the fastly metrics on Grafana

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/infra#237]
**Is your feature request related to a problem? Please describe.**

Fastly exposes a fair amount of metrics on the binary cache usage. A number of them are aggregated and made available as a csv under some magic s3 urls. This is very useful information and it would be great to be able to access it more easily.

**Describe the solution you'd like**

Expose this data on https://status.nixos.org/grafana

**Additional context**

https://www.notion.so/nixos-foundation/Metrics-a891b87f6a6d46ad93b3aaa09b09320b#9b25d9286c4247f98375a6e78ca75a8e

**Comment by delroth** [comment]
> Netlify exposes a fair amount of metrics on the binary cache usage.

Do you mean s/netlify/fastly/ then?

**Comment by thufschmitt** [comment]
> > Netlify exposes a fair amount of metrics on the binary cache usage.
> 
> Do you mean s/netlify/fastly/ then?

Duh yes, thanks. I've corrected that in the issue

**Comment by delroth** [comment]
I'll try to have a look this week.

**Comment by delroth** [comment]
https://monitoring.nixos.org/grafana/d/SHjM6e-ik/fastly?orgId=1

If anything more specific is needed please list what would be useful to have :)
