### ISSUE TITLE
Rename repo to "infra"

### ISSUE THREAD

**Issue by zimbatm** [NixOS/infra#359]
**Is your feature request related to a problem? Please describe.**

The repo name is a pain to type.

**Describe the solution you'd like**

Rename it to something short like "infra". That way it would also match the team name.

**Describe alternatives you've considered**

Learn to type faster.

**Additional context**

Since it's a matter of personal preference, I propose to simply vote yes/no and adopt the change if there is a clear majority only.

**Comment by cole-h** [comment]
I know GitHub will handle redirects for us, but we should still make sure that anything that refers to `nixos-org-configurations` gets the updated name, too.

**Comment by mweinelt** [comment]
Let's go and do the rename. We can start updating references right after.

**Comment by zimbatm** [comment]
:tada:
