### ISSUE TITLE
Clarify existing licensing and apply MIT license

### ISSUE THREAD

**Issue by mweinelt** [NixOS/infra#370]
The repo is currently published without a license, which is not ideal for reusability or for porting things into nixpkgs, which requires contributions to be MIT licensed.

I think going for MIT would be easiest, but I'm open to discussing alternatives. Also, we would need the sign-off of every previous contributor, which feels like a daunting task.

* [x] @edolstra
* [x] @grahamc
* [x] @zimbatm
* [x] @delroth
* [x] @rbvermaa
* [x] @mweinelt
* [x] @cole-h
* [x] @lheckemann
* [x] @garbas
* [x] @vcunat
* [x] @JulienMalka
* [x] @domenkozar
* [x] @LnL7

**Comment by edolstra** [comment]
Probably not worth it, given that this is an "internal" repo. But we could ask that any new contributions are MIT-licensed.

**Comment by delroth** [comment]
Very similar precedent: https://github.com/NixOS/nixos-search/pull/723

Let's start by figuring out how many contributors we'd need to get an approval from to relicense. I agree that MIT licensing makes the most sense to align with every other official NixOS-related project. I'm reasonably happy with using the same guideline/threshold as nixos-search, aka. "more than 100 lines contributed".

**Comment by vcunat** [comment]
Only 9 of them over 100 lines I think: https://github.com/NixOS/infra/graphs/contributors

But I'm no lawyer; not sure how safe it is to use such a simple metric.

**Comment by zimbatm** [comment]
I hereby agree to release all my changes under the MIT :+1: 

(also created the list above)

**Comment by JulienMalka** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by rbvermaa** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by delroth** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by vcunat** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by domenkozar** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by garbas** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by mweinelt** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by lheckemann** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by cole-h** [comment]
I hereby agree to release all my changes under the MIT 👍

**Comment by grahamc** [comment]
MIT seems good!

**Comment by LnL7** [comment]
Fine by me, MIT is what I generally use myself.

**Comment by vcunat** [comment]
Done.
