### ISSUE TITLE
Decommission eris.nixos.org

### ISSUE THREAD

**Issue by mweinelt** [NixOS/infra#386]
We want to retire this machine, and are replacing it with pluto.nixos.org.

Its services need to be migrated before that can happen:
- [x] netboot
- [x] rfc39
- [x] prometheus
- [x] grafana
- [x] victoriametrics (nixos-metrics)

The earliest possible cancellation date is 28 February 2024. Renewal is likely monthly.

**Comment by delroth** [comment]
Configs deleted and contract cancelled.
