### ISSUE TITLE
vaultwarden: smtp credentials invalid

### ISSUE THREAD

**Issue by mweinelt** [NixOS/infra#430]
**Affected service**
vault.nixos.org

**Describe the issue**
When inviting a user an error appears, that says SMTP authentication failed. An invitation is therefore never sent.

**System information**
 [2024-05-23 07:28:30.393][vaultwarden::mail][ERROR] SMTP 5xx error: permanent error (535): 5.7.8 Error: authentication failed:  - Authentication credentials invalid

**Comment by zimbatm** [comment]
Let's use a local mailer like the NixOS wiki?

**Comment by zimbatm** [comment]
We discuss this during the infra meeting. The easiest would be to use the same technique as the wiki: https://github.com/NixOS/nixos-wiki-infra/blob/main/modules/postfix.nix
