### ISSUE TITLE
Host experimental-nix-installer binaries

### ISSUE THREAD

**Issue by mkenigs** [NixOS/infra#452]
We would like to move towards hosting builds of https://github.com/NixOS/experimental-nix-installer somewhere official. I've copied some more explanation of context from @abathur below from Matrix.

The current state of builds of the installer is that there's Hydra jobset that builds it. @domenkozar put together a CI action that grabs builds of the installer from Hydra and commits them to the prerelease branch of experimental-nix-installer. There's a [script on main](https://github.com/NixOS/experimental-nix-installer/blob/main/nix-installer.sh) that will detect your arch and grab a binary from the prelease branch.

For comparison, DetSys runs a script that uploads installers to S3, and then they have a script at https://install.determinate.systems/nix that will detect your arch and download the correct installer. Alternatively, you can use the URL to an arch specific installer directly, e.g. https://install.determinate.systems/nix/nix-installer-x86_64-linux.

The official Nix installer is somewhat similar with a detection script at https://nixos.org/nix/install.

I think ideally we'd like to work towards some URL under nixos.org, but we'd love some input from the infra team on next steps.

Ping @zimbatm 

Some more background from @abathur
> Open-ended query since I'm not sure what we need, but we're hoping to (eventually) get installers derived from https://github.com/NixOS/experimental-nix-installer (in turn forked from the detsys installer) hosted somewhere ~official.
>
> Background: back in early 2023 there was general interest in adopting something based on their installer, but a few things were clear:
>
> the Nix team wanted changes (broadly: disabling telemetry and reverting opinionated bits)
> the detsys folks don't see it as their place to push
> the Nix team doesn't have bandwidth to pull
> Since that sounded like an impasse, I suggested a more modest initial goal of standing up an official-experimental installer. That enables the few of us involved that aren't aligned with the Nix team or detsys (so far mainly Matthew Kenigsberg and myself) to whittle away at the needed changes, sort out how to get it built and published on official infra, start cultivating the Nix team's confidence in the installer by encouraging regulars to give it a shake, and ultimately try to shrink the final adoption decision to something that fits on the Nix team's plate.
>
> This has taken a while to ripen since we ended up waiting for some refactoring on the detsys end, but I think it's close now.
>
> Upstream's existing release workflows upload to S3, so that's likely the low-friction path (but IIRC they're also taking advantage of some enterprise runners that I don't think we have access to). We also already have a hydra jobset.
>
> I imagine this ends up being incremental with one or more approval steps before it actually ends up accessible somewhere under nixos.org.

**Comment by zimbatm** [comment]
Sweet, thanks for working on this!

One option is to store the release artefacts on GitHub Releases.
This has the advantage of keeping coordination and team interdependency to a minimum, and Github pays for the hosting.

In that model, you would:
1. Use GitHub Actions to build (or pull from Hydra) and publish the releases.
2. The release can also include the trampoline shell script. (so users can `curl https://github.com/NixOS/nix-installer/releases/download/v1.2.3/install.sh | bash` to target a specific release of the installer).
3. Add a redirect to the website from https://nixos.org/nix/install-experimental to the latest installer release.

**Comment by mkenigs** [comment]
Thanks for the help @zimbatm ! Sounds good to me if it's good with @abathur

**Comment by zimbatm** [comment]
Ok, in that case, we can close this issue, as you should be able to do (1) and (2) on your own. But let me know if you want any pointers!

For (3), talk to the marketing team as they own https://github.com/nixos/nixos-homepage
