### ISSUE TITLE
Request: S3 bucket for ofborg's TF state

### ISSUE THREAD

**Issue by cole-h** [NixOS/infra#455]
Hello infra!

Recently, I've done some work to make ofborg's infrastructure more accessible to people who are not me.

The final piece of the puzzle is an S3 bucket (which is used for ofborg's TF state). Right now, it lives in an S3 bucket controlled by Graham.

As soon as we can move this to a foundation-owned bucket (and have some way of getting credentials to access that bucket), I'll be able to trivially give infra-build access to everything and stop being the blocker for most things (while also increasing the bus factor).

Let me know if there's any additional information that would make this go smoother!

**Comment by zimbatm** [comment]
Hey Cole,

Greate idea.

For the S3 bucket, you should be able to access the terraform state bucket we're already using in the infra repo. Ping me on Matrix otherwise.

**Comment by cole-h** [comment]
I forgot we were using a unified state bucket. I was able to get it all setup by following the setup in the `terraform` directory (for those with access, you'll see a new `ofborg` directory containing its state files). One step closer to making it easier for others to collaborate on the ofborg infrastructure. (I need to do some tidying and fix-uping, but that should be done by the end of the month.)

Thanks for the pointer, that helped a ton!
